apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ .Release.Name }}-scaledobject
  namespace: demo
spec:
  scaleTargetRef:
    name: demo-app-deployment
  pollingInterval: 10
  cooldownPeriod: 10
  minReplicaCount: 1
  maxReplicaCount: 10
  triggers:
  - type: metrics-api
    metadata:
      targetValue: "1"
      url: http://sample-app-service.demo.svc.cluster.local:8000/
      valueLocation: "place.demoes.count"