apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
  namespace: demo
  labels:
    app: {{ .Release.Name }}-app
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-app
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}